### ISSUE TITLE
bsm/openrtb

### ISSUE THREAD

**Issue by stokito** [prebid/openrtb#3]
The https://github.com/bsm/openrtb provides DTOs and is a much popular library (259 stars). 
Can you merge code from the library or migrate to it?
https://github.com/bsm/openrtb/issues/94

**Comment by SyntaxNode** [comment]
This project is maintained by [Prebid.org](prebid.org) and is used by [Prebid Server](https://github.com/prebid/prebid-server), among other projects. You are welcomed to use the https://github.com/bsm/openrtb package if you prefer their object model or code styling. Your choice and no hard feelings.

You asked us to merge code from that project. I see in the linked issue reference to `ContentCategory`. That enumeration is used for the fields `bcat`, `app.cat`, `site.cat`, `content.cat`, and `bid.cat`. This project defines these fields as string arrays which is appropriate because the exact enumeration is specified by the `cattax` field (category taxonomy).

I have no objection to specifying the defined category taxonomy enumerations and keeping the `cat` fields as a string array. Would that help you in your projects?

**Comment by stokito** [comment]
Thank you, I'm not insist just see that we have a duplicated work here.

**Comment by SyntaxNode** [comment]
Ok. Is there anything else you'd like to discuss on this thread or shall we close the discussion?
